platform :ios, '12.0'
use_frameworks!

def my_pods
  pod 'RxSwift'
  pod 'SwiftyJSON'
  pod 'Gifu'
end

target 'iGif' do
  my_pods
end

target 'iGifTests' do
  my_pods
  pod 'Nimble'
  pod 'RxNimble'
  pod 'RxBlocking'
  pod 'OHHTTPStubs/Swift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
